# -*- coding: utf-8 -*-
###############################################################################
#
#    Tech-Receptives Solutions Pvt. Ltd.
#    Copyright (C) 2009-TODAY Tech-Receptives(<http://www.techreceptives.com>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

from openerp import models, fields


class OpMarksheetRegister(models.Model):
    _name = 'op.marksheet.register'

    name = fields.Char('Marksheet Register')
    exam_id = fields.Many2one('op.exam', 'Exam', select=True)
    batch_id = fields.Many2one('op.batch', 'Batch', related='exam_id.batch_id',
        store=True, select=True, readonly=True)
    course_id = fields.Many2one('op.course', 'Course', related='exam_id.course_id',
        store=True, select=True, readonly=True)
    marksheet_ids = fields.One2many('op.marksheet', 'marksheet_register_id', 'Marksheets',
        ondelete='cascade')
    declare_date = fields.Date('Generated Date')
    generated_by = fields.Many2one(
        'res.users', 'Generated By')
    state = fields.Selection(
        [('draft', 'Draft'), ('validated', 'Validated'),
         ('cancelled', 'Cancelled')], 'Status', default='draft')
    total_passed = fields.Float('Total Pass')
    total_failed = fields.Float('Total Fail')

